apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector: # deployment - pod 대응용
    matchLabels:
      app: web
  template: # 여기서부터 파드 템플릿
    metadata:
      labels:
        app: web # 파드의 라벨
    spec:
      containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
  type: NodePort
